codeigniter:
  build: dockerfiles/codeigniter
  ports:
    - "80:80"
  volumes:
      - ./codeigniter:/web
  hostname: codeigniter

mysql:
  build: dockerfiles/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
  hostname: mysql
