codeigniter:
  build: dockerfiles/codeigniter
  ports:
    - "80:80"
  volumes:
      - ./code/codeigniter:/web
      - ./hosts:/etc/hosts
  hostname: codeigniter

mysql:
  build: dockerfiles/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
  hostname: mysql
